name: Terraform CI/CD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


permissions:
  id-token: write
  contents: read        

jobs:
  terraform-cleanup:
    name: Post Apply Cleanup
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.13.3'
      TF_LINT_VERSION: '0.59.1'
    
    steps:
    - name: Checkout Github repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: arn:aws:iam::529088282444:role/my-git-aws-action
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
        
    - name: terraform init
      working-directory: ./modules/networking
      run: terraform init


    - name: terraform plan Destroy
      working-directory: ./modules/networking
      run: terraform plan -destroy -out=tfplan-destroy

    - name: terraform apply Destroy
      working-directory: ./modules/networking
      run: terraform apply -auto-approve tfplan-destroy   

